on:
  push: null

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'

      - run: cabal configure --flags pedantic

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store  }}
          key: ${{ hashFiles('cabal.project.freeze') }}

      - run: cabal build --only-dependencies

      - run: cabal build

      - run: cabal sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist-newstyle/sdist/prolude-*.tar.gz
          name: prolude-${{ github.sha }}.tar.gz

      - run: cabal check
